export const FIELD_NAMES = {
  name: 'Company name',
  firstName: 'First name',
  lastName: 'Last name',
  username: 'Username',
  gender: 'Gender',
  address: 'Address',
  phone: 'Phone',
  type: 'Type',
  email: 'Email',
  country: 'Country',
  chargeAmount: 'Charge Amount',
  vatAmount: 'VAT Amount',
  currency: 'Currency',
  password: 'Password',
  image: 'Upload an Image',
};

export const FIELD_TYPES = {
  name: 'text',
  address: 'text',
  firstName: 'text',
  lastName: 'text',
  username: 'text',
  phone: 'text',
  type: 'text',
  gender: 'text',
  currency: 'text',
  country: 'text',
  email: 'email',
  chargeAmount: 'number',
  vatAmount: 'number',
  password: 'password',
};
