import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { auth } from '@/auth';
import { SessionProvider } from 'next-auth/react';
import CommonNavbar from './(Components)/CommonNavbar';
import Navbar from './(Components)/Navbar';
import DashboardWrapper from './(root)/dashboardWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <DashboardWrapper session={session}>
            {' '}
            {session ? <Navbar /> : <CommonNavbar />}
            {children}
          </DashboardWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
